### ISSUE TITLE
News feed duplication bug on cryptonews app

### ISSUE THREAD

**Issue by Emmexdee** [Johnesan/CryptoNews#1]
#### Expected behavior
When you load the application news feed should come in singly the without replication of the same news

#### Actual behavior
At page load there is duplication of news feeds which causes redundancy.

#### How to reproduce
1.	Open the news app for the first time
2.	Wait for news to fetch from sites and scroll down.

•	Device: Samsung J7 Pro

•	Operating system: Android OS 7.0.1 Nougat

•	RAM: 3GB

•	App version: 2.0.

#### Recording Of The Bug
<div style="position:relative;height:0;padding-bottom:75.0%"><iframe src="https://www.youtube.com/embed/1RqyOC9eYQI?ecver=2" width="480" height="360" frameborder="0" allow="autoplay; encrypted-media" style="position:absolute;width:100%;height:100%;left:0" allowfullscreen></iframe></div>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@emmexdee/news-feed-duplication-bug-on-cryptonews-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by Johnesan** [comment]
Thank you for identifying this. I hadn't noticed this behavior before now. I sure would look into it and fix the issue.

**Comment by Johnesan** [comment]
This issue has now been fixed.
